language: c++
sudo: false

compiler:
    - clang
    - gcc

addons:
  apt:
    packages:
    - libncurses5-dev
    - libreadline-dev
    - openssl
    - libgnutls-dev
    - libexpat1-dev
    - zlib1g-dev
    - build-essential
    - automake
    - autoconf
    - autopoint
    - gperf

script:
    - ./bootstrap
    - ./configure
    - make release-check
